version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          working_directory: ~/project/src
          name: 'Install project dependencies'
          command: dotnet restore
      - run:
          working_directory: ~/project/src
          name: 'Run Application Tests'
          command: dotnet test -v n --logger trx --results-directory:../TestResults --collect:"Code Coverage" --no-restore
      - run:
          working_directory: ~/project
          name: 'Publish test results'
          when: always
          command: |
            dotnet tool install -g trx2junit
            export PATH="${PATH}:/root/.dotnet/tools"
            trx2junit TestResults/*.trx
      - store_test_results:
          path: ~/project/TestResults
      - store_artifacts:
          path: ~/project/TestResults
          destination: TestResults

      - run:
          working_directory: ~/project/src
          name: 'Print Working Directory'
          command: pwd

  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          working_directory: ~/project/src
          name: 'Build Application according to some given configuration'
          command: dotnet build --configuration Release

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
