version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0 #circleci/node:7.10
    working_directory: ~/work
    steps:
      - run: dotnet build

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    working_directory: ~/work
    steps:
      - run: dotnet test

  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    working_directory: ~/work
    steps:
      - run: echo deploy step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
